name: CI

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run make
      id: make
      run: |
        make bind9.conf hosts.txt
        echo ::set-output name=tag::v$(date +%Y%m%d)
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.make.outputs.tag }}
        release_name: Release ${{ steps.make.outputs.tag }}
        draft: false
        prerelease: false
    - name: Upload hosts.txt
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hosts.txt
        asset_name: hosts.txt
        asset_content_type: text/plain
    - name: Upload bind9.conf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bind9.conf
        asset_name: bind9.conf
        asset_content_type: text/plain
